apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pqfv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-pqfv@sha256:2bc88be24560fd7f6eab794f09f5e04b50fa7d0cd9f6c26b128fbc1578517144
        name: my-nodejs
        resources: {}
status: {}
